language: python
python:
  - "3.5"
install:
  - sudo apt-add-repository -y ppa:picaso/octave;
  - sudo apt-get update -qq;
  - sudo apt-get install -qq octave liboctave-dev;
  - pip install ipykernel jupyter_client traitlets jupyter_kernel_test flit
  - flit install
  - python -m octave_kernel.install
script:
  - make test
