language: python
dist: trusty
python:
  - "2.7"
  - "3.5"
install:
  - sudo apt-add-repository -y ppa:octave/stable;
  - sudo apt-get update -qq;
  - sudo apt-get install -qq octave liboctave-dev gnuplot-x11;
  - pip install .
  - python -m octave_kernel.install
script:
  - make test
